export const BUY_CAKE = 'BUY_CAKE' ;
export const BUY_ICECREAM = 'BUY_ICECREAM' ;

export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST' ;
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS' ;
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR' ;